title: Voorwaardelijk gedrag met if/else
hero_image: images/banner.png
description: Voorwaardelijk gedrag met if/else
version: 4
listed: false
copyedit: false
last_tested: "2021-11-22"
steps:
  - 
    title: Voorwaardelijk gedrag met if/else
