title: Comportement conditionnel avec if/else
hero_image: images/banner.png
description: Comportement conditionnel avec if/else
version: 4
listed: false
copyedit: false
last_tested: "2021-11-22"
steps:
  - 
    title: Comportement conditionnel avec if/else
